log_name: "classifier_training_0313"
seed: 0
device: "cuda:3"  # auto | cpu | cuda | cuda:0

torch_deterministic: false
cudnn_benchmark: true
allow_tf32: true
torch_num_threads: 0


# Reward config path for fail/reward recomputation.
# If terrain_config_path is set, it has higher priority.
terrain_config: "terrain_config.yaml"


# Folders containing collision_failures.pkl and failure_summary.csv.
# Supports absolute path or path relative to this file.
log_dirs:
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001124"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001128"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001145"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001150"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001156"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001651"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001657"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_001701"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_143421"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_143429"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_143435"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_143443"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_143450"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_173144"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_173157"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_173207"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_173215"
  - "../train_SAC/eval_logs/random_eval_0327_20260328_173234"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_161840"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_161851"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_161855"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_161903"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_161909"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_162003"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_162012"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_162021"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_162028"
#  - "../train_SAC/eval_logs/random_eval_0329_20260329_162039"

# When consecutive fail+stuck frames appear, keep only the first K fail frames.
consecutive_fail_keep_k: 1


states_logs:
  # default output dir: ./states_logs/<log_name>
  log_name: "0327_random"


classifier:
  # default output dir: ./classifier/<log_name>
  log_name: "classifier_0316"
  concat_action_to_obs: False  # true: classifier input = obs + action, false: obs only
  # Mark failure frame and its previous k frames as positive labels.
  fail_preceding_k: 10
  val_split: 0.1
  test_split: 0.1
  epochs: 1000
  batch_size: 512
  learning_rate: 0.0005
  hidden_dim: 128
  pos_weight: 1.6

  save_every_epochs: 10
  checkpoint_every_epochs: 10
  smooth_window: 10
