go2_task: "terrain"
go2_config: "go2.yaml"

terrain_config: "terrain_config.yaml"

mode_y: 10
mode_x: 10
generations: 10
popsize: 8
sigma: 0.8
seed: 0

# Trig terrain amplitude max. Effective range becomes [-terrain_amplitude_max, terrain_amplitude_max].
terrain_amplitude_max: 1.0

max_robot_steps: 350
safe_radius_m: 1.0
blend_radius_m: 2.0

log_name: "cmaes_logs_0309"
